homeassistant:
  name: Yelhome
  latitude: 32.06
  longitude: 34.80
  elevation: 36
  unit_system: metric
  time_zone: Asia/Jerusalem
  customize: !include customize.yaml

frontend:

config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

mqtt:

updater:

discovery:

conversation:

history:

logbook:

map:

sun:

sensor:
  - platform: yr

ifttt:
  key: !secret ifttt_key

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
